doc.type.html
script
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
filename=covidstrings28gamecode.js
java.awt graphics 
div id=header></div
audio=new audio(audio_file mp3)
audio.play 
random button
new button(set random color)
option button
new  button (change color)
public fun with graphics(){
color panel=new j panel();
this add (panel,center)
button panel
new  panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13),(rnextint(13)))
buttonpanel.add(option button);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel,borderlayout.south)
public static main(string [] args)
jframe f = new covid strings28()
f.set title(covid strings28)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult == x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.inner html=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covid strings team list28=[pink covid disease fighters,orange rna messengers,indigo isos,black night riders,red protein spikers,violet,burgundy,purple]
covid strings phrase list28=[ non-concatenated strings "covid abzymes might provide an answer to long covid symptoms"
"a covid tracker has more tech than the chevy tracker"
"its abbreviation cannot be cts"
"nor could it be shortened to trax"
"the nfls covid policy at least regular season-wise will not involve any sort of bubble"
"post-season wise covid rosters would be even larger"
"even playoff expansion could have been on the table"
"at least2020 for the nfl was better than the xfl"
concatenated strings 
"the"+"only"+"number"+"we"+"may"+"see"+"involving"+"covid"+"freedom"+"may"+"be"+"cx-3"
"c30"+"in"+"this"+"regard"+"is"+"a"+"stretch"
"covid"+"will"+"probably"+"not"+"be"+"eliminated"+"in"+"2080"+"either"
"if"+"covid"+"had"+"ions"+"they"+"wouldnt"+"be"+"related"+"to"+"the"+"saturn"+"ion"
"should"+"covid"+"germs"+"travel"+"they"+"can"+"easily"+"make"+"self"+"quarantining"+"self"+"evident"
"one"+"covid"+"miracle"+"though"+"involves"+"vaccines"
"red"+"flags"+"covid"+"wise"+"are"+"not"+"just"+"limited"+"to"+"china"
"covid"+"fraud"+"is"+"one"+"example"]
covid strings multiple choice list28=[1:a enzymes b snake oil c light therapy d abzymes,2:a miracle b congress passing ukraine aid c vaccines d preventing y2k38,3:a impala b malibu c traverse d tracker,4: a red flags b former presidents kids working at the world bank c in the pluralist theory for mid-east peace d the drafting of the canuck letter,5:a track mark b trax c relay d ev5000,6:a2050 b2040 c2080 d3550,6:a ct4 b cts c xlr d sts,7:a50 b70 c9 d3,8:a post b regular c mid d pro bowl,9:a injured reserve lists b fatalities c rosters d bubbles,10:a c3po b c30 c a covid free future d sharknados,11:a contraction b expansion c sameness d crossover,12:a relay b flexstreme c ion d prevue,13:a stay at home b travel c die out d become twisters,14:a stuffing b fraud c freedom d anarchy,15:a china b america c south korea d the winklevoss bitcoin operation,16:a putins b a bunch of rich people c anyone adding graphine to fabrics d the cambodian prime ministers]
covid strings28 math problems list=[ non-concatenated "if a line on a covid tracker was pointing upward what would the relationship be"?,"if the line on the covid tracker had a slope of3 and a y intercept of0 what would the y coordinate be at2"?,"if the covid point of (2,6) was rotated270 degrees counterclockwise what is the new point"?,"if the new point was reflected across the y axis what is the new point"?,"if the previous point was translated2 units to the left and18 units up what is the new point"?,"if the previous point was translated8 units to the right and5/4units up what is the new point"?,
concatenated "if"+"a"+"poll"+"found"+"that"+"52.5"+"percent"+"disapprove"+"of"+"the"+"nfls"+"covid"+"policy"+"what"+"percent"+"approve"?,"if"+"37.25"+"percent"+"strongly"+"disapprove"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"10.55"+"percent"+"what"+"is"+"the"+"range"?,"if"+"a"+"poll"+"found"+"67"+"percent"+"believe"+"that"+"the"+"nfl"+"should"+"potentially"+"consider"+"playoff"+"expansion"+"due"+"to"+"covid"+"what"+"percent"+"dont"?,"if"+"55"+"percent"+"strongly"+"believe"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"7.08"+"percent"+"what"+"is"+"the"+"range"?] 
covid strings scrambled phrase list28=["ovicd"+"ractker","ovicd"+"erd"+"glafs",bonus "ovicd"+"heift"+"fo"+"tatse"]
covid strings sentence list28=["china certainly is in the running for most covid red flags","covid fraud was not as bad as the amount of money that putins friends have"]
userin.select team
import meta.
class myclass
constructor(non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax
chart js 
def gradient
id=mygradient
gradientunits=userspaceonuse
if functionslope>=1:
return direct relationship
else:
return no relationship
x1=0
y1=0
x2=2
y2=x2(3)
stop offset=0 stop-color=ff0000
stop offset=1 stop color=0000ff
<lineargradient>
<filter
id=linear1
filterunits=objectboundingbox
x=0%
y=0%
width=100%
height=100%
<fecomponenttransfer>
<fefunccovidstrings type=linear slope>=1
transformationlist=[reflection,rotation,translation]
if transformation==rotation270 degrees counter-clockwise:
shift270 degrees-counterclockwise
else:
remain
if transformation ==reflection y axis:
shift y axis
else:
remain
if transformation==translation(2,18):
shift2 units right,18units up :
else:
remain
if (s1.length())!=s2.length: 
return false
if s1.length()==s2.length:
return true
char[]arr1=s1.tochararray
char [] arr2= s2.tochararray
arrays.sort(arr1)
arrays.sort(arr2)
for(int i=1; i<s1.length();i++)}
string s11=s1.substring(0,i)
strings12=s1.substring(i,s1.length());
strings13=s1.substring(i,s1.length()-i());
strings21=s2.substring(0,i)
string22=s2.substring(0,s2.length()-i);
if transformation==translation(8,5/4):
shift8 units right5/4units up:
else:
remain
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct:
return false
else:
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
if users team wins covid strings28 
console log users team wins covid strings28 
else
return game over
return filename





